[package]
name = "vmm0"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kvm-ioctls = "0.10.0"
kvm-bindings = "0.5.0"
libc = "0.2.103"
